version: "3.7"

services:
    library:
        build: ./app
        image: papers-library:1.0
        ports:
            - 5000:5000
        depends_on: 
            - mongodb
        networks:
            - backend

    mongodb:
        image: mongo:bionic
        restart: always
        # To reset the db: docker-compose down --volumes
        # https://stackoverflow.com/a/52509946/844372
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    mongodbdata:
        driver: local
        